
# Site settings
title: Personal Page
name: Xingbin
subtitle: Financial Economist
email: paul.soto@upf.edu
description: >
  Financial Economist
baseurl: ""
url: "https://morty9527.github.io/"
github_username:  morty9527
disqus_baseurl: "https://morty9527.github.io/"
disqus_shortname: https-morty9527-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Xingbin"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: morty9527
    url: https://github.com/morty9527
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://linkedin.com
    desc: Connect with me on LinkedIn
    share: true
